### ISSUE TITLE
🐛 Bug: "Are The Types Wrong?" Block includes ? in output GHA

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/create-typescript-app#1855]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

If `blockAreTheTypesWrong` is included, it should create a `ci.yml` workflow with a valid name.

```yml
jobs:
  are_the_types_wrong:
    name: Are The Types Wrong?
```

### Actual

I'm seeing it generate:

```yml
jobs:
  are_the_types_wrong?:
    name: Are The Types Wrong?
```

### Additional Info

Prototyped in #1839.

💖
